### PR TITLE
initialize app only when there are no existing app.

### PR DESCRIPTION
**Pull request by spankie**

### CODE REVIEW

**Comment by raja-anbazhagan** [comment]
Your logic would only make sense if this piece of code is called multiple times. The current implementation creates a single bean which will be used throughout the rest of the code.

**Comment by spankie** [comment]
When ever I run the app there is an exception that says "app with name new-app already exists". that is why I added the code. Even I am surprised as to why that would be the case.

**Comment by raja-anbazhagan** [comment]
@spankie One way to know for sure. Place a breakpoint within the code and debug to see if the code is called somewhere else.

I will always be able to help if you can share the codebase or snippet that you are using.

**Comment by spankie** [comment]
I think the reason why it happens is because i added devtools that reloads the app when a change occurs. here is a very short video showing what I am talking about. https://www.loom.com/share/9883938c27bf44d483e769c2d0f82cd9

**Pull request closed without merging**
